name: envoy
version: master
summary: C++ front/service proxy
description: |
  Envoy is an L7 proxy and communication bus designed for large modern service
  oriented architectures.

grade: devel
confinement: devmode

apps:
  envoy:
    command: source/exe/envoy
    plugs: [network, network-bind]

parts:
  envoy:
    source: .
    plugin: cmake
    configflags:
      - "-DENVOY_DEBUG:BOOL=OFF"
      - "-DENVOY_STRIP:BOOL=ON"
      - "-DCLANG-FORMAT:FILEPATH=clang-format"
      - "-DCMAKE_CXX_FLAGS=-static-libstdc++"
      - "-DENVOY_COTIRE_MODULE_DIR:FILEPATH=$SNAPCRAFT_STAGE/cotire/CMake"
      - "-DENVOY_PROTOBUF_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_PROTOBUF_PROTOC:FILEPATH=$SNAPCRAFT_STAGE/bin/protoc"
      - "-DENVOY_SPDLOG_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_LIBEVENT_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_HTTP_PARSER_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_LIGHTSTEP_TRACER_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_NGHTTP2_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_RAPIDJSON_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_GPERFTOOLS_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_GTEST_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_TCLAP_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_GMOCK_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_OPENSSL_INCLUDE_DIR:FILEPATH=$SNAPCRAFT_STAGE/include"
      - "-DENVOY_EXE_EXTRA_LINKER_FLAGS:STRING=-L$SNAPCRAFT_STAGE/lib"
    make-parameters: [envoy]
    artifacts:
      - source/exe/envoy
    after:
      - gcc
      - cotire
      - protobuf
      - spdlog
      - libevent
      - http-parser
      - lightstep
      - nghttp2
      - rapidjson
      - gperftools
      - tclap
      - googletest
      - boringssl
      - c-ares

  gcc:
    source: http://www.netgull.com/gcc/releases/gcc-4.9.4/gcc-4.9.4.tar.gz
    plugin: autotools
    configflags: ['--enable-languages=c,c++']
    build-packages: [libmpc-dev]

  cotire:
    source: https://github.com/sakra/cotire/archive/cotire-1.7.8.tar.gz
    plugin: dump
    organize:
      "*": cotire/
    prime:
      - -*

  protobuf:
    source: https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz
    plugin: autotools
    build-packages: [gcc]

  spdlog:
    source: https://github.com/gabime/spdlog/archive/v0.11.0.tar.gz
    plugin: dump
    prime:
      - include
    after: [cotire]

  libevent:
    source: https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz
    plugin: autotools
    configflags:
      - --enable-share=no
      - --disable-libevent-regress
      - --disable-openssl

  http-parser:
    source: https://github.com/nodejs/http-parser/archive/v2.7.0.tar.gz
    plugin: dump
    build: |
      gcc -O2 -c http_parser.c -o http_parser.o
      ar rcs libhttp_parser.a http_parser.o
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/lib/
      cp libhttp_parser.a $SNAPCRAFT_PART_INSTALL/lib/
      mkdir $SNAPCRAFT_PART_INSTALL/include
      cp http_parser.h $SNAPCRAFT_PART_INSTALL/include/

  lightstep:
    source: https://github.com/lightstep/lightstep-tracer-cpp/releases/download/v0_36/lightstep-tracer-cpp-0.36.tar.gz
    plugin: autotools
    configflags:
      - --disable-grpc
      - --enable-shared=no
      - protobuf_CFLAGS="-I$SNAPCRAFT_STAGE/include"
      - protobuf_LIBS="-L$SNAPCRAFT_STAGE/lib -lprotobuf"
      - PROTOC=$SNAPCRAFT_STAGE/bin/protoc
    after: [protobuf]

  nghttp2:
    source: https://github.com/nghttp2/nghttp2/releases/download/v1.20.0/nghttp2-1.20.0.tar.gz
    plugin: autotools
    configflags:
      - --enable-shared=no
      - --enable-lib-only

  rapidjson:
    source: https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz
    plugin: dump
    stage:
      - include
      - bin
    after: [spdlog]

  gperftools:
    source: https://github.com/gperftools/gperftools/releases/download/gperftools-2.5/gperftools-2.5.tar.gz
    plugin: autotools
    configflags:
      - --enable-shared=no
      - --enable-frame-pointers

  tclap:
    source: https://sourceforge.net/projects/tclap/files/tclap-1.2.1.tar.gz/download
    source-type: tar
    plugin: dump
    stage:
      - include/tclap
    after: [spdlog]

  googletest:
    source: https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    plugin: cmake
    prime:
      - -*

  boringssl:
    source: https://boringssl.googlesource.com/boringssl
    source-type: git
    source-commit: b87c80300647c2c0311c1489a104470e099f1531
    plugin: cmake
    build-packages: [golang-go]
    build: |
      cmake .
      make
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/include
      mv include/openssl/ $SNAPCRAFT_PART_INSTALL/include/
      mkdir $SNAPCRAFT_PART_INSTALL/lib
      cp ssl/libssl.a $SNAPCRAFT_PART_INSTALL/lib
      cp crypto/libcrypto.a $SNAPCRAFT_PART_INSTALL/lib

  c-ares:
    source: https://github.com/c-ares/c-ares/archive/cares-1_12_0.tar.gz
    plugin: autotools
    configflags: ['CFLAGS=']
